### PR TITLE
feat: enable blog

### PR DESCRIPTION
**Pull request by kirederik**
## Description
This relates to issue #117

### CODE REVIEW

**Comment by kirederik** [comment]
@catmo-syntasso plis boss

**Comment by catmo-syntasso** [comment]
Screenshot 2024-10-07 at 10 24 17
Me problem or build problem?

**Comment by kirederik** [comment]
@catmo-syntasso `yarn install` 🙏🏽

**Review by catmo-syntasso — APPROVED** [review]
For those following along, it was a me problem

**Pull request merged**
