### PR TITLE
SKE backstage generator auth via imagePullSecret

### PR DESCRIPTION
**Pull request by SaphMB**
Document how to use imagePullSecret for pulling the SKE generator image

### CODE REVIEW

**Comment by kirederik** [comment]
is it worthy adding an admonition to say the secret must exist on the `kratix-platform-system` namespace + all other namespaces users can send resource requests from?

**Comment by SaphMB** [comment]
Good point @kirederik, I'll make that tweak

**Comment by SaphMB** [comment]
Added the following @kirederik :

image

**Review by kirederik — APPROVED** [review]

**Comment by kirederik** [comment]
Looks good! I'll merge it since i'm already here 😆

**Pull request merged**
